### ISSUE TITLE
How does this confusion relate to progurad?

### ISSUE THREAD

**Issue by fendo8888** [robtimus/obfuscation-spring#2]
How does this confusion relate to progurad? don't know how to use

**Comment by robtimus** [comment]
I'm assuming you're talking about [ProGuard](https://www.guardsquare.com/proguard). If so, then there is no relation at all. Whereas ProGuard can obfuscate your application itself, this library can obfuscate text _inside_ an application. That can be logged text or injected properties. The latter is mostly useful when they are logged or otherwise printed; logging an `Obfuscated` value will not log the value itself but instead an obfuscate version of it (e.g. `***`).
